states = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

statesVoted = {
    "AL": "Republican",
    "AK": "Republican",
    "AZ": "Democrat",
    "AR": "Republican",
    "CA": "Democrat",
    "CO": "Democrat",
    "CT": "Democrat",
    "DE": "Democrat",
    "FL": "Republican",
    "GA": "Democrat",
    "HI": "Democrat",
    "ID": "Republican",
    "IL": "Democrat",
    "IN": "Republican",
    "IA": "Republican",
    "KS": "Republican",
    "KY": "Republican",
    "LA": "Republican",
    "ME": "Democrat",
    "MD": "Democrat",
    "MA": "Democrat",
    "MI": "Democrat",
    "MN": "Democrat",
    "MS": "Republican",
    "MO": "Republican",
    "MT": "Republican",
    "NE": "Republican",
    "NV": "Democrat",
    "NH": "Democrat",
    "NJ": "Democrat",
    "NM": "Democrat",
    "NY": "Democrat",
    "NC": "Republican",
    "ND": "Republican",
    "OH": "Republican",
    "OK": "Republican",
    "OR": "Democrat",
    "PA": "Democrat",
    "RI": "Democrat",
    "SC": "Republican",
    "SD": "Republican",
    "TN": "Republican",
    "TX": "Republican",
    "UT": "Republican",
    "VT": "Democrat",
    "VA": "Democrat",
    "WA": "Democrat",
    "WV": "Republican",
    "WI": "Democrat",
    "WY": "Republican"
}

#source = https://worldpopulationreview.com/state-rankings/average-iq-by-state
states_iq = {
    "AL": 95.7,
    "AK": 99,
    "AZ": 97.4,
    "AR": 97.5,
    "CA": 95.5,
    "CO": 101.6,
    "CT": 103.1,
    "DE": 100.4,
    "FL": 98.4,
    "GA": 98,
    "HI": 95.6,
    "ID": 101.4,
    "IL": 99.9,
    "IN": 101.7,
    "IA": 103.2,
    "KS": 102.8,
    "KY": 99.4,
    "LA": 95.3,
    "ME": 103.4,
    "MD": 99.7,
    "MA": 104.3,
    "MI": 100.5,
    "MN": 103.7,
    "MS": 94.2,
    "MO": 101,
    "MT": 103.4,
    "NE": 102.3,
    "NV": 96.5,
    "NH": 104.2,
    "NJ": 102.8,
    "NM": 95.7,
    "NY": 100.7,
    "NC": 100.2,
    "ND": 103.8,
    "OH": 101.8,
    "OK": 99.3,
    "OR": 101.2,
    "PA": 101.5,
    "RI": 99.5,
    "SC": 98.4,
    "SD": 102.8,
    "TN": 97.7,
    "TX": 100,
    "UT": 101.1,
    "VT": 103.8,
    "VA": 101.9,
    "WA": 101.9,
    "WV": 98.7,
    "WI": 102.9,
    "WY": 102.4
}
