states = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

statesVoted = {
    "AL": "Republican",
    "AK": "Republican",
    "AZ": "Democrat",
    "AR": "Republican",
    "CA": "Democrat",
    "CO": "Democrat",
    "CT": "Democrat",
    "DE": "Democrat",
    "FL": "Republican",
    "GA": "Democrat",
    "HI": "Democrat",
    "ID": "Republican",
    "IL": "Democrat",
    "IN": "Republican",
    "IA": "Republican",
    "KS": "Republican",
    "KY": "Republican",
    "LA": "Republican",
    "ME": "Democrat",
    "MD": "Democrat",
    "MA": "Democrat",
    "MI": "Democrat",
    "MN": "Democrat",
    "MS": "Republican",
    "MO": "Republican",
    "MT": "Republican",
    "NE": "Republican",
    "NV": "Democrat",
    "NH": "Democrat",
    "NJ": "Democrat",
    "NM": "Democrat",
    "NY": "Democrat",
    "NC": "Republican",
    "ND": "Republican",
    "OH": "Republican",
    "OK": "Republican",
    "OR": "Democrat",
    "PA": "Democrat",
    "RI": "Democrat",
    "SC": "Republican",
    "SD": "Republican",
    "TN": "Republican",
    "TX": "Republican",
    "UT": "Republican",
    "VT": "Democrat",
    "VA": "Democrat",
    "WA": "Democrat",
    "WV": "Republican",
    "WI": "Democrat",
    "WY": "Republican"
}
